#!/bin/bash

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║   Kaya Keyboard Monitoring - Grant Accessibility Permission    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Get the venv Python path
VENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.venv"
PYTHON_PATH="$VENV_DIR/bin/python"
PYTHON3_PATH="$VENV_DIR/bin/python3"

echo "✓ Venv directory: $VENV_DIR"
echo "✓ Python executable: $PYTHON_PATH"
echo "✓ Python3 executable: $PYTHON3_PATH"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "GRANT ACCESSIBILITY PERMISSION"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Follow these steps to enable keyboard capture:"
echo ""
echo "1. Open System Settings (⌘ + Space, type 'System Settings', press Enter)"
echo ""
echo "2. Navigate to: Privacy & Security → Accessibility"
echo ""
echo "3. Click the + (plus) button to add an application"
echo ""
echo "4. Copy this path and paste it in the file dialog:"
echo "   $PYTHON_PATH"
echo ""
echo "5. Select it and click 'Open'"
echo ""
echo "6. You should now see Python in the Accessibility list"
echo ""
echo "7. Restart the Kaya app:"
echo "   .venv/bin/python main.py"
echo ""
echo "8. Type something - keystrokes should now appear in the terminal!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Troubleshooting:"
echo "  • If nothing still appears, try adding $PYTHON3_PATH instead"
echo "  • You may need to restart the terminal or reboot after granting permission"
echo "  • Verify permission was granted by checking System Settings again"
